version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000" # PHP-FPM hanya untuk internal
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306" # Hanya expose kalau kamu mau akses MySQL dari luar
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" # Ganti dari 80 ke 8080 karena VPS kamu udah pakai port 80
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

volumes:
  mysql_data:


networks:
  laravel:
